file <- "household_power_consumption.txt";
datum <- read.table(file, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".");
data_interval <- datum[datum$Date %in% c("1/2/2007","2/2/2007") ,];
date_and_time <- strptime(paste(data_interval$Date, data_interval$Time, sep=" "), "%d/%m/%Y %H:%M:%S");
power <- as.numeric(data_interval$Global_active_power);
rpower <- as.numeric(data_interval$Global_reactive_power);
volt <- as.numeric(data_interval$Voltage);
sm1 <- as.numeric(data_interval$Sub_metering_1);
sm2 <- as.numeric(data_interval$Sub_metering_2);
sm3 <- as.numeric(data_interval$Sub_metering_3);
png("plot4.png", width=480, height=480);
par(mfrow = c(2, 2));
plot(date_and_time, power, type="l", xlab="", ylab="Global active power", cex=0.2);
plot(date_and_time, volt, type="l", ylab="Voltage");
plot(date_and_time, sm1, type="l", ylab="Energy submetering", xlab="");
lines(date_and_time, sm2, type="l", col="red");
lines(date_and_time, sm3, type="l", col="blue");
legend("topright", c("Sub-metering 1", "Sub-metering 2", "Sub-metering 3"), lty=, lwd=2.5, col=c("black", "red", "blue"));
plot(date_and_time, rpower, type="l", ylab="Global reactive power");
dev.off();